In [81]:
###Data Ingestion

import pandas as pd
import numpy as np

In [82]:
df=pd.read_csv('houseprice.csv',usecols=["SalePrice", "MSSubClass", "MSZoning", "LotFrontage", "LotArea", "Street", "YearBuilt", "LotShape", "1stFlrSF", "2ndFlrSF"]).dropna()

In [83]:
df.shape

(1201, 10)

In [84]:
df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  YearBuilt  \
0          60       RL         65.0     8450   Pave      Reg       2003   
1          20       RL         80.0     9600   Pave      Reg       1976   
2          60       RL         68.0    11250   Pave      IR1       2001   
3          70       RL         60.0     9550   Pave      IR1       1915   
4          60       RL         84.0    14260   Pave      IR1       2000   

   1stFlrSF  2ndFlrSF  SalePrice  
0       856       854     208500  
1      1262         0     181500  
2       920       866     223500  
3       961       756     140000  
4      1145      1053     250000

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1201 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MSSubClass   1201 non-null   int64  
 1   MSZoning     1201 non-null   object 
 2   LotFrontage  1201 non-null   float64
 3   LotArea      1201 non-null   int64  
 4   Street       1201 non-null   object 
 5   LotShape     1201 non-null   object 
 6   YearBuilt    1201 non-null   int64  
 7   1stFlrSF     1201 non-null   int64  
 8   2ndFlrSF     1201 non-null   int64  
 9   SalePrice    1201 non-null   int64  
dtypes: float64(1), int64(6), object(3)
memory usage: 103.2+ KB


In [86]:
import datetime
datetime.datetime.now().year

2023

In [87]:
df['Total Years']=datetime.datetime.now().year-df['YearBuilt']

In [88]:
df.drop("YearBuilt",axis=1,inplace=True)

In [89]:
df.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', '1stFlrSF', '2ndFlrSF', 'SalePrice', 'Total Years'],
      dtype='object')

In [90]:
###Creating my Categorical Columns

In [91]:
cat_features=["MSSubClass", "MSZoning", "Street", "LotShape"]
out_feature="SalePrice"

In [92]:
###Label Encoding

from sklearn.preprocessing import LabelEncoder
lbl_encoders={}
for feature in cat_features:
    lbl_encoders[feature]=LabelEncoder()
    df[feature]=lbl_encoders[feature].fit_transform(df[feature])

In [93]:
df

MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  1stFlrSF  \
0              5         3         65.0     8450       1         3       856   
1              0         3         80.0     9600       1         3      1262   
2              5         3         68.0    11250       1         0       920   
3              6         3         60.0     9550       1         0       961   
4              5         3         84.0    14260       1         0      1145   
...          ...       ...          ...      ...     ...       ...       ...   
1455           5         3         62.0     7917       1         3       953   
1456           0         3         85.0    13175       1         3      2073   
1457           6         3         66.0     9042       1         3      1188   
1458           0         3         68.0     9717       1         3      1078   
1459           0         3         75.0     9937       1         3      1256   

      2ndFlrSF  SalePrice  Total Years  
0          854     208500           20  
1            0     181500           47  
2          866     223500           22  
3          756     140000          108  
4         1053     250000           23  
...        ...        ...          ...  
1455       694     175000           24  
1456         0     210000           45  
1457      1152     266500           82  
1458         0     142125           73  
1459         0     147500           58  

[1201 rows x 10 columns]

In [94]:
### Stacking and Converting Into Tensors
cat_features=np.stack([df['MSSubClass'],df['MSZoning'],df['Street'],df['LotShape']],1)
cat_features

array([[5, 3, 1, 3],
       [0, 3, 1, 3],
       [5, 3, 1, 0],
       ...,
       [6, 3, 1, 3],
       [0, 3, 1, 3],
       [0, 3, 1, 3]], dtype=int64)

In [95]:
### Convert numpy to Tensors
import torch
cat_features=torch.tensor(cat_features,dtype=torch.int64)
cat_features

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])

In [96]:
#### create continuous variable
cont_features=[]
for i in df.columns:
    if i in ["MSSubClass", "MSZoning", "Street", "LotShape","SalePrice"]:
        pass
    else:
        cont_features.append(i)

In [97]:
cont_features

['LotFrontage', 'LotArea', '1stFlrSF', '2ndFlrSF', 'Total Years']

In [98]:
### Stacking continuous variable to a tensor
cont_values=np.stack([df[i].values for i in cont_features],axis=1)
cont_values=torch.tensor(cont_values,dtype=torch.float)
cont_values

tensor([[   65.,  8450.,   856.,   854.,    20.],
        [   80.,  9600.,  1262.,     0.,    47.],
        [   68., 11250.,   920.,   866.,    22.],
        ...,
        [   66.,  9042.,  1188.,  1152.,    82.],
        [   68.,  9717.,  1078.,     0.,    73.],
        [   75.,  9937.,  1256.,     0.,    58.]])

In [99]:
cont_values.dtype

torch.float32

In [100]:
### Dependent Feature 
y=torch.tensor(df['SalePrice'].values,dtype=torch.float).reshape(-1,1)
y

tensor([[208500.],
        [181500.],
        [223500.],
        ...,
        [266500.],
        [142125.],
        [147500.]])

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1201 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MSSubClass   1201 non-null   int64  
 1   MSZoning     1201 non-null   int32  
 2   LotFrontage  1201 non-null   float64
 3   LotArea      1201 non-null   int64  
 4   Street       1201 non-null   int32  
 5   LotShape     1201 non-null   int32  
 6   1stFlrSF     1201 non-null   int64  
 7   2ndFlrSF     1201 non-null   int64  
 8   SalePrice    1201 non-null   int64  
 9   Total Years  1201 non-null   int64  
dtypes: float64(1), int32(3), int64(6)
memory usage: 89.1 KB


In [102]:
cat_features.shape,cont_values.shape,y.shape

(torch.Size([1201, 4]), torch.Size([1201, 5]), torch.Size([1201, 1]))

In [103]:
len(df['MSSubClass'].unique())

15

In [104]:
#### Embedding Size For Categorical columns
cat_dims=[len(df[col].unique()) for col in ["MSSubClass", "MSZoning", "Street", "LotShape"]]
cat_dims

[15, 5, 2, 4]

In [105]:
embedding_dim= [(x, min(50, (x + 1) // 2)) for x in cat_dims]
embedding_dim

[(15, 8), (5, 3), (2, 1), (4, 2)]

In [106]:
###creating the Embedding Layer

In [107]:
import torch
import torch.nn as nn
import torch.nn.functional as F
embed_representation=nn.ModuleList([nn.Embedding(inp,out) for inp,out in embedding_dim])
embed_representation

ModuleList(
  (0): Embedding(15, 8)
  (1): Embedding(5, 3)
  (2): Embedding(2, 1)
  (3): Embedding(4, 2)
)

In [108]:
cat_features

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])

In [109]:
cat_featuresz=cat_features[:4]
cat_featuresz

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        [6, 3, 1, 0]])

In [110]:
pd.set_option('display.max_rows', 500)
embedding_val=[]
for i,e in enumerate(embed_representation):
    embedding_val.append(e(cat_features[:,i]))
embedding_val

[tensor([[-0.5943,  1.3361, -0.2407,  ...,  0.3392,  0.2584,  0.8634],
         [ 0.6085,  0.4155, -0.2119,  ...,  0.8640,  2.2847, -1.9048],
         [-0.5943,  1.3361, -0.2407,  ...,  0.3392,  0.2584,  0.8634],
         ...,
         [ 2.9678, -0.7569, -1.5468,  ...,  0.7889,  0.3029,  0.2303],
         [ 0.6085,  0.4155, -0.2119,  ...,  0.8640,  2.2847, -1.9048],
         [ 0.6085,  0.4155, -0.2119,  ...,  0.8640,  2.2847, -1.9048]],
        grad_fn=<EmbeddingBackward0>),
 tensor([[-0.5473, -1.0473,  0.2751],
         [-0.5473, -1.0473,  0.2751],
         [-0.5473, -1.0473,  0.2751],
         ...,
         [-0.5473, -1.0473,  0.2751],
         [-0.5473, -1.0473,  0.2751],
         [-0.5473, -1.0473,  0.2751]], grad_fn=<EmbeddingBackward0>),
 tensor([[-0.3642],
         [-0.3642],
         [-0.3642],
         ...,
         [-0.3642],
         [-0.3642],
         [-0.3642]], grad_fn=<EmbeddingBackward0>),
 tensor([[-0.5624,  1.5390],
         [-0.5624,  1.5390],
         [ 0.1403,  0.

In [111]:
z = torch.cat(embedding_val, 1)
z

tensor([[-0.5943,  1.3361, -0.2407,  ..., -0.3642, -0.5624,  1.5390],
        [ 0.6085,  0.4155, -0.2119,  ..., -0.3642, -0.5624,  1.5390],
        [-0.5943,  1.3361, -0.2407,  ..., -0.3642,  0.1403,  0.9060],
        ...,
        [ 2.9678, -0.7569, -1.5468,  ..., -0.3642, -0.5624,  1.5390],
        [ 0.6085,  0.4155, -0.2119,  ..., -0.3642, -0.5624,  1.5390],
        [ 0.6085,  0.4155, -0.2119,  ..., -0.3642, -0.5624,  1.5390]],
       grad_fn=<CatBackward0>)

In [112]:
#### Implement dropupout
droput=nn.Dropout(.4)
final_embed=droput(z)
final_embed

tensor([[-0.9905,  2.2269, -0.0000,  ..., -0.6070, -0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.3532,  ..., -0.6070, -0.9373,  2.5650],
        [-0.9905,  2.2269, -0.0000,  ..., -0.6070,  0.0000,  0.0000],
        ...,
        [ 0.0000, -1.2615, -2.5780,  ..., -0.6070, -0.9373,  2.5650],
        [ 0.0000,  0.0000, -0.3532,  ..., -0.0000, -0.0000,  2.5650],
        [ 1.0142,  0.6924, -0.3532,  ..., -0.0000, -0.0000,  0.0000]],
       grad_fn=<MulBackward0>)

In [113]:
##### Create a Feed Forward Neural Network
import torch
import torch.nn as nn
import torch.nn.functional as F
class FeedForwardNN(nn.Module):

    def __init__(self, embedding_dim, n_cont, out_sz, layers, p=0.5):
        super().__init__()
        self.embeds = nn.ModuleList([nn.Embedding(inp,out) for inp,out in embedding_dim])
        self.emb_drop = nn.Dropout(p)
        self.bn_cont = nn.BatchNorm1d(n_cont)
        
        layerlist = []
        n_emb = sum((out for inp,out in embedding_dim))
        n_in = n_emb + n_cont
        
        for i in layers:
            layerlist.append(nn.Linear(n_in,i)) 
            layerlist.append(nn.ReLU(inplace=True))
            layerlist.append(nn.BatchNorm1d(i))
            layerlist.append(nn.Dropout(p))
            n_in = i
        layerlist.append(nn.Linear(layers[-1],out_sz))
            
        self.layers = nn.Sequential(*layerlist)
    
    def forward(self, x_cat, x_cont):
        embeddings = []
        for i,e in enumerate(self.embeds):
            embeddings.append(e(x_cat[:,i]))
        x = torch.cat(embeddings, 1)
        x = self.emb_drop(x)
        x_cont = self.bn_cont(x_cont)
        x = torch.cat([x, x_cont], 1)
        x = self.layers(x)
        return x

In [114]:
torch.manual_seed(100)
model=FeedForwardNN(embedding_dim,len(cont_features),1,[100,50],p=0.4)

In [115]:
model

FeedForwardNN(
  (embeds): ModuleList(
    (0): Embedding(15, 8)
    (1): Embedding(5, 3)
    (2): Embedding(2, 1)
    (3): Embedding(4, 2)
  )
  (emb_drop): Dropout(p=0.4, inplace=False)
  (bn_cont): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layers): Sequential(
    (0): Linear(in_features=19, out_features=100, bias=True)
    (1): ReLU(inplace=True)
    (2): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=100, out_features=50, bias=True)
    (5): ReLU(inplace=True)
    (6): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): Dropout(p=0.4, inplace=False)
    (8): Linear(in_features=50, out_features=1, bias=True)
  )
)

In [116]:
##Define Loss and Optimizer

In [117]:
loss_function=nn.MSELoss()
optimizer=torch.optim.Adam(model.parameters(),lr=0.01)

In [118]:
df.shape

(1201, 10)

In [120]:
cont_values

tensor([[   65.,  8450.,   856.,   854.,    20.],
        [   80.,  9600.,  1262.,     0.,    47.],
        [   68., 11250.,   920.,   866.,    22.],
        ...,
        [   66.,  9042.,  1188.,  1152.,    82.],
        [   68.,  9717.,  1078.,     0.,    73.],
        [   75.,  9937.,  1256.,     0.,    58.]])

In [121]:
cont_values.shape

torch.Size([1201, 5])

In [122]:
batch_size=1200
test_size=int(batch_size*0.15)
train_categorical=cat_features[:batch_size-test_size]
test_categorical=cat_features[batch_size-test_size:batch_size]
train_cont=cont_values[:batch_size-test_size]
test_cont=cont_values[batch_size-test_size:batch_size]
y_train=y[:batch_size-test_size]
y_test=y[batch_size-test_size:batch_size]

In [123]:
len(train_categorical),len(test_categorical),len(train_cont),len(test_cont),len(y_train),len(y_test)

(1020, 180, 1020, 180, 1020, 180)

In [124]:
epochs=5000
final_losses=[]
for i in range(epochs):
    i=i+1
    y_pred=model(train_categorical,train_cont)
    loss=torch.sqrt(loss_function(y_pred,y_train)) ### RMSE
    final_losses.append(loss)
    if i%10==1:
        print("Epoch number: {} and the loss : {}".format(i,loss.item()))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

Epoch number: 1 and the loss : 200496.75
Epoch number: 11 and the loss : 200493.46875
Epoch number: 21 and the loss : 200489.140625
Epoch number: 31 and the loss : 200482.640625
Epoch number: 41 and the loss : 200473.25
Epoch number: 51 and the loss : 200461.375
Epoch number: 61 and the loss : 200446.40625
Epoch number: 71 and the loss : 200429.359375
Epoch number: 81 and the loss : 200408.0
Epoch number: 91 and the loss : 200383.421875
Epoch number: 101 and the loss : 200355.3125
Epoch number: 111 and the loss : 200322.125
Epoch number: 121 and the loss : 200291.4375
Epoch number: 131 and the loss : 200252.015625
Epoch number: 141 and the loss : 200206.625
Epoch number: 151 and the loss : 200162.234375
Epoch number: 161 and the loss : 200112.265625
Epoch number: 171 and the loss : 200059.6875
Epoch number: 181 and the loss : 200005.890625
Epoch number: 191 and the loss : 199946.34375
Epoch number: 201 and the loss : 199881.921875
Epoch number: 211 and the loss : 199815.953125
Epoch nu

In [125]:
#### Validate the Test Data
y_pred=""
with torch.no_grad():
    y_pred=model(test_categorical,test_cont)
    loss=torch.sqrt(loss_function(y_pred,y_test))
print('RMSE: {}'.format(loss))

RMSE: 43480.23828125


In [126]:
data_verify=pd.DataFrame(y_test.tolist(),columns=["Test"])
data_predicted=pd.DataFrame(y_pred.tolist(),columns=["Prediction"])

In [127]:
data_predicted

Prediction
0    141363.046875
1    203064.421875
2    149078.593750
3    223752.953125
4    217793.937500
5    207789.671875
6    141771.328125
7    300268.500000
8    161741.625000
9    363545.000000
10   197839.875000
11   176815.890625
12   193296.140625
13   107246.757812
14   221082.890625
15   127525.531250
16   240583.312500
17   123827.148438
18   327495.031250
19    82758.437500
20   193832.703125
21   112210.960938
22    91688.054688
23   194836.609375
24   213117.140625
25   181179.296875
26   139580.250000
27   345456.156250
28   150122.328125
29   158179.046875
30    78208.414062
31   125276.921875
32   273688.593750
33    66641.445312
34   226857.234375
35   200851.140625
36   114243.835938
37   129822.851562
38   139840.406250
39   123252.679688
40   249807.421875
41   323918.031250
42    91529.898438
43   157018.421875
44   196957.281250
45    93104.867188
46   102670.914062
47   140353.875000
48   185001.828125
49   395746.218750
50   132864.140625
51   340201.531250
52   216353.015625
53   142947.078125
54   273735.625000
55   192995.656250
56   129484.164062
57   124695.531250
58   288252.531250
59   180738.828125
60   340714.281250
61   109151.804688
62   232807.062500
63   227957.968750
64   161753.718750
65   128961.882812
66   154256.281250
67   256822.937500
68    66423.265625
69   259617.390625
70    95062.781250
71    74198.703125
72    75442.093750
73   280135.312500
74   196501.265625
75   222601.234375
76   140266.609375
77    88845.023438
78   136744.296875
79   116605.851562
80   145623.671875
81   117513.820312
82    92643.906250
83   247624.062500
84   107310.445312
85   101364.460938
86   153770.796875
87   133281.546875
88   126947.187500
89   101452.656250
90   297161.156250
91   112595.945312
92   158861.375000
93   131886.046875
94   122702.851562
95   429320.281250
96   200437.234375
97   352928.750000
98   265903.312500
99   254231.609375
100  168235.078125
101  160601.390625
102  227699.296875
103  103036.921875
104  249268.578125
105  146508.203125
106  153164.515625
107  257694.171875
108  279994.718750
109  239957.781250
110  103541.460938
111  131493.671875
112   54240.785156
113  186015.781250
114  115867.226562
115  144462.937500
116  121242.187500
117  113663.492188
118  402947.187500
119  286290.062500
120  209668.375000
121  108439.273438
122  163250.109375
123  117218.109375
124  104228.320312
125  142978.500000
126  207314.359375
127  328689.968750
128   91852.492188
129  168704.406250
130  104959.210938
131  125672.492188
132  200572.234375
133  173573.734375
134  246352.015625
135  110944.742188
136  305167.593750
137  127088.070312
138  136676.656250
139  233327.343750
140  230916.765625
141  153720.171875
142   68661.265625
143  309187.156250
144  167310.921875
145  260863.703125
146  140637.875000
147  142235.640625
148  135557.484375
149  129614.617188
150  124906.929688
151  130412.609375
152  210873.671875
153  130448.921875
154   94623.539062
155  219664.796875
156  100764.335938
157  188090.265625
158  159298.046875
159  162750.078125
160  116087.414062
161  316303.093750
162  134557.671875
163  183084.171875
164  208657.796875
165  346602.312500
166  196991.796875
167   91490.414062
168  271028.843750
169  109293.171875
170   79043.601562
171  120715.179688
172  292941.156250
173   95315.171875
174  157948.421875
175  182000.640625
176  172426.031250
177  289399.843750
178  231804.187500
179  115544.304688

In [128]:
final_output=pd.concat([data_verify,data_predicted],axis=1)
final_output['Difference']=final_output['Test']-final_output['Prediction']
final_output.head()

Test     Prediction    Difference
0  130000.0  141363.046875 -11363.046875
1  138887.0  203064.421875 -64177.421875
2  175500.0  149078.593750  26421.406250
3  195000.0  223752.953125 -28752.953125
4  142500.0  217793.937500 -75293.937500

In [129]:
#### Saving The Model
#### Save the model
torch.save(model,'HousePrice.pt')

In [130]:
model=torch.load('HousePrice.pt')

In [131]:
model.eval()

FeedForwardNN(
  (embeds): ModuleList(
    (0): Embedding(15, 8)
    (1): Embedding(5, 3)
    (2): Embedding(2, 1)
    (3): Embedding(4, 2)
  )
  (emb_drop): Dropout(p=0.4, inplace=False)
  (bn_cont): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layers): Sequential(
    (0): Linear(in_features=19, out_features=100, bias=True)
    (1): ReLU(inplace=True)
    (2): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=100, out_features=50, bias=True)
    (5): ReLU(inplace=True)
    (6): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): Dropout(p=0.4, inplace=False)
    (8): Linear(in_features=50, out_features=1, bias=True)
  )
)